/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiWorkshopImagesRouteImport } from './routes/api/workshop-images'
import { Route as AppPresencaIndexRouteImport } from './routes/app/presenca/index'
import { Route as AppOficinasIndexRouteImport } from './routes/app/oficinas/index'
import { Route as AppInscricoesIndexRouteImport } from './routes/app/inscricoes/index'
import { Route as AppEquipeIndexRouteImport } from './routes/app/equipe/index'
import { Route as AppCertificadosIndexRouteImport } from './routes/app/certificados/index'
import { Route as AppAlunosIndexRouteImport } from './routes/app/alunos/index'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiWorkshopImagesRoute = ApiWorkshopImagesRouteImport.update({
  id: '/api/workshop-images',
  path: '/api/workshop-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPresencaIndexRoute = AppPresencaIndexRouteImport.update({
  id: '/presenca/',
  path: '/presenca/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOficinasIndexRoute = AppOficinasIndexRouteImport.update({
  id: '/oficinas/',
  path: '/oficinas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInscricoesIndexRoute = AppInscricoesIndexRouteImport.update({
  id: '/inscricoes/',
  path: '/inscricoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEquipeIndexRoute = AppEquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCertificadosIndexRoute = AppCertificadosIndexRouteImport.update({
  id: '/certificados/',
  path: '/certificados/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlunosIndexRoute = AppAlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/workshop-images': typeof ApiWorkshopImagesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/app/alunos/': typeof AppAlunosIndexRoute
  '/app/certificados/': typeof AppCertificadosIndexRoute
  '/app/equipe/': typeof AppEquipeIndexRoute
  '/app/inscricoes/': typeof AppInscricoesIndexRoute
  '/app/oficinas/': typeof AppOficinasIndexRoute
  '/app/presenca/': typeof AppPresencaIndexRoute
}
export interface FileRoutesByTo {
  '/api/workshop-images': typeof ApiWorkshopImagesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/app/alunos': typeof AppAlunosIndexRoute
  '/app/certificados': typeof AppCertificadosIndexRoute
  '/app/equipe': typeof AppEquipeIndexRoute
  '/app/inscricoes': typeof AppInscricoesIndexRoute
  '/app/oficinas': typeof AppOficinasIndexRoute
  '/app/presenca': typeof AppPresencaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/workshop-images': typeof ApiWorkshopImagesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/app/alunos/': typeof AppAlunosIndexRoute
  '/app/certificados/': typeof AppCertificadosIndexRoute
  '/app/equipe/': typeof AppEquipeIndexRoute
  '/app/inscricoes/': typeof AppInscricoesIndexRoute
  '/app/oficinas/': typeof AppOficinasIndexRoute
  '/app/presenca/': typeof AppPresencaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/auth'
    | '/api/workshop-images'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/app/'
    | '/auth/'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/app/alunos/'
    | '/app/certificados/'
    | '/app/equipe/'
    | '/app/inscricoes/'
    | '/app/oficinas/'
    | '/app/presenca/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/workshop-images'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/app'
    | '/auth'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/app/alunos'
    | '/app/certificados'
    | '/app/equipe'
    | '/app/inscricoes'
    | '/app/oficinas'
    | '/app/presenca'
  id:
    | '__root__'
    | '/app'
    | '/auth'
    | '/api/workshop-images'
    | '/auth/login'
    | '/auth/signup'
    | '/_public/'
    | '/app/'
    | '/auth/'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/app/alunos/'
    | '/app/certificados/'
    | '/app/equipe/'
    | '/app/inscricoes/'
    | '/app/oficinas/'
    | '/app/presenca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiWorkshopImagesRoute: typeof ApiWorkshopImagesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/workshop-images': {
      id: '/api/workshop-images'
      path: '/api/workshop-images'
      fullPath: '/api/workshop-images'
      preLoaderRoute: typeof ApiWorkshopImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/presenca/': {
      id: '/app/presenca/'
      path: '/presenca'
      fullPath: '/app/presenca/'
      preLoaderRoute: typeof AppPresencaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/oficinas/': {
      id: '/app/oficinas/'
      path: '/oficinas'
      fullPath: '/app/oficinas/'
      preLoaderRoute: typeof AppOficinasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inscricoes/': {
      id: '/app/inscricoes/'
      path: '/inscricoes'
      fullPath: '/app/inscricoes/'
      preLoaderRoute: typeof AppInscricoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/equipe/': {
      id: '/app/equipe/'
      path: '/equipe'
      fullPath: '/app/equipe/'
      preLoaderRoute: typeof AppEquipeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/certificados/': {
      id: '/app/certificados/'
      path: '/certificados'
      fullPath: '/app/certificados/'
      preLoaderRoute: typeof AppCertificadosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alunos/': {
      id: '/app/alunos/'
      path: '/alunos'
      fullPath: '/app/alunos/'
      preLoaderRoute: typeof AppAlunosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAlunosIndexRoute: typeof AppAlunosIndexRoute
  AppCertificadosIndexRoute: typeof AppCertificadosIndexRoute
  AppEquipeIndexRoute: typeof AppEquipeIndexRoute
  AppInscricoesIndexRoute: typeof AppInscricoesIndexRoute
  AppOficinasIndexRoute: typeof AppOficinasIndexRoute
  AppPresencaIndexRoute: typeof AppPresencaIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAlunosIndexRoute: AppAlunosIndexRoute,
  AppCertificadosIndexRoute: AppCertificadosIndexRoute,
  AppEquipeIndexRoute: AppEquipeIndexRoute,
  AppInscricoesIndexRoute: AppInscricoesIndexRoute,
  AppOficinasIndexRoute: AppOficinasIndexRoute,
  AppPresencaIndexRoute: AppPresencaIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiWorkshopImagesRoute: ApiWorkshopImagesRoute,
  PublicIndexRoute: PublicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
